var data = [

    {
        "id":0,
        "route":"0",
        "parent":"data",
        "title":"文件",
        "type":"file",
        "child":[
            {
                "id":0,
                "route":"0_0",
                "parent":"file",
                "title":"全部",
                "type":"all",
                "child":[
                    {
                        "id":0,
                        "route":"0_0_0",
                        "parent":"all",
                        "title":"QQ",
                        "type":"qq",
                        "child":[
                            {
                                "id":0,
                                "route":"0_0_0_0",
                                "parent":"QQ",
                                "title":"QQ22",
                                "type":"qq",
                                "child":[

                                ]
                            },
                            {
                                "id":1,
                                "route":"0_0_0_1",
                                "parent":"QQ",
                                "title":"QQ3333",
                                "type":"qq",
                                "child":[

                                ]
                            }
                        ]
                    },
                    {
                        "id":1,
                        "route":"0_0_1",
                        "parent":"all",
                        "title":"QQ网盘",
                        "type":"qqwp",
                        "child":[

                        ]
                    },
                    {
                        "id":2,
                        "route":"0_0_2",
                        "parent":"all",
                        "title":"QQ音乐",
                        "type":"music",
                        "child":[

                        ]
                    },
                    {
                        "id":3,
                        "route":"0_0_3",
                        "parent":"all",
                        "title":"QQ邮箱",
                        "type":"emil",
                        "child":[

                        ]
                    },
                    {
                        "id":4,
                        "route":"0_0_4",
                        "parent":"all",
                        "title":"网络收藏夹",
                        "type":"shoucang",
                        "child":[

                        ]
                    }
                ]
            },
            {
                "id":1,
                "route":"0_1",
                "parent":"file",
                "title":"图片",
                "type":"pic",
                "child":[]
            },
            {
                "id":2,
                "route":"0_2",
                "parent":"file",
                "title":"文档",
                "type":"document",
                "child":[]
            },
            {
                "id":3,
                "route":"0_3",
                "parent":"file",
                "title":"视频",
                "type":"video",
                "child":[]
            },
            {
                "id":4,
                "route":"0_4",
                "parent":"file",
                "title":"笔记",
                "type":"biji",
                "child":[]
            },
            {
                "id":5,
                "route":"0_5",
                "parent":"file",
                "title":"音乐",
                "type":"music",
                "child":[
                    {
                        "id":0,
                        "route":"0_5_0",
                        "parent":"all",
                        "title":"QQ222222222",
                        "type":"qq",
                        "child":[

                        ]
                    },
                    {
                        "id":1,
                        "route":"0_5_1",
                        "parent":"all",
                        "title":"QQ网盘",
                        "type":"qqwp",
                        "child":[

                        ]
                    },
                    {
                        "id":2,
                        "route":"0_5_2",
                        "parent":"all",
                        "title":"QQ音乐",
                        "type":"music",
                        "child":[

                        ]
                    },
                    {
                        "id":3,
                        "route":"0_5_3",
                        "parent":"all",
                        "title":"QQ邮箱",
                        "type":"emil",
                        "child":[

                        ]
                    },
                    {
                        "id":4,
                        "route":"0_5_4",
                        "parent":"all",
                        "title":"网络收藏夹",
                        "type":"shoucang",
                        "child":[

                        ]
                    }
                ]
            }
        ]
    }
];
